[package]
authors.workspace = true
categories = ["data-structures", "database"]
description = "rusqlite × Polars bridge library"
documentation = "https://docs.rs/polite/"
edition.workspace = true
homepage.workspace = true
keywords = ["bridge", "dataframe", "polars", "sqlite"]
license.workspace = true
name = "polite"
readme = "README.md"
repository.workspace = true
version = "0.1.2"

[dependencies]
chrono.workspace = true
connectorx.workspace = true
polars.workspace = true
rusqlite.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow = "1.0.99"
eyre.workspace = true
insta.workspace = true
tempfile.workspace = true

[package.metadata.cargo-machete]
ignored = ["chrono"]
